# Paw tmux statusline
set -g status on
set -g status-bg "#1a1720"
set -g status-fg "#f5e9f5"
set -g status-left-length 40
set -g status-left "#[fg=#ff4fb2,bold] #S #[fg=#5b4d66]│ "
set -g status-right "#[fg=#b24dff]%H:%M #[fg=#5b4d66]│#[fg=#c792ea] #h "
setw -g window-status-format "#[fg=#5b4d66] #I:#W "
setw -g window-status-current-format "#[fg=#1a1720,bg=#ff4fb2,bold] #I:#W "
set -g pane-active-border-style "fg=#ff4fb2"
set -g pane-border-style "fg=#2a2530"
